export { MedicoService } from './medico/medico.service';
import { HospitalService } from './hospital/hospital.service';
export { UploadService } from './upload/upload.service';
export { LoginGuardGuard } from './guards/login-guard.guard';
export { UsuarioService } from './usuario/usuario.service';
export { SettingsService } from './settings/settings.service';
export { SharedService } from './shared/shared.service';
export { SidebarService } from './shared/sidebar.service';
export { HospitalService } from './hospital/hospital.service';
